/*.$file${..\src::Controller.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: growing_champer.qm
* File:  ${..\src::Controller.h}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${..\src::Controller.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef CONTROLLER_H
#define CONTROLLER_H
#include "qpn.h"

enum Controller_Signals
{
    SETTING_SIG = Q_USER_SIG,
    MAX_SIG,
    START_SIG,
    CAUTION_SIG_SIG,
    TIME_TICK_SIG,
    BACK_SIG,
    CW_SIG,
    CCW_SIG,
    TEMP_SET_SIG,
    HUMI_SET_SIG,
    TIMER_BACK_SIG,
    IGNORED_SIG,
    TICK_SIG,
    Max_SIG
};

/*.$declare${Hsm::Controller_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${Hsm::Controller_ctor} .................................................*/
void Controller_ctor(void);
/*.$enddecl${Hsm::Controller_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif